/** Mirrors `finance_common.types.Category` values for manual entry. */
export const MANUAL_TX_CATEGORIES = [
  'Food Delivery',
  'Groceries',
  'Dining Out',
  'Outside Food & Snacks',
  'Transport & Fuel',
  'Car Expenses',
  'Housing & Rent',
  'Utilities',
  'Health & Medical',
  'Clothing',
  'Online Shopping',
  'Entertainment',
  'Subscriptions',
  'Education',
  'Personal Care',
  'Personal Grooming',
  'Travel',
  'Relatives Visit',
  'Gifts & Donations',
  'Gifts & Additionals',
  'EMI Loan Repayment',
  'CC Bill',
  'Investments',
  'Insurance',
  'Taxes',
  'Income',
  'Transfer',
  'Other',
] as const

/** Mirrors `finance_common.types.PaymentMode` values. */
export const PAYMENT_MODE_OPTIONS = [
  'UPI',
  'Cash',
  'HDFC Credit Card',
  'SBI Credit Card',
  'ICICI Credit Card',
  'Axis Credit Card',
  'Other Credit Card',
  'HDFC Debit Card',
  'SBI Debit Card',
  'Bank Transfer',
  'NEFT/IMPS',
  'EMI',
  'Other',
] as const
