"""FY report PDF (ReportLab)."""

from __future__ import annotations

from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def build_fy_pdf(
    *,
    fy_label: str,
    rows: list[tuple[str, int]],
    total_spent_paise: int,
    income_run_rate_annual_paise: int,
    implied_savings_paise: int,
) -> bytes:
    """Return PDF bytes for an FY summary + month table."""
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )
    styles = getSampleStyleSheet()
    story: list = [
        Paragraph(f"<b>Personal Finance OS — FY {fy_label}</b>", styles["Title"]),
        Spacer(1, 0.5 * cm),
        Paragraph(
            f"Total spent (FY): ₹{total_spent_paise / 100:,.2f}<br/>"
            f"Income run-rate (annual): ₹{income_run_rate_annual_paise / 100:,.2f}<br/>"
            f"Implied savings vs spend: ₹{implied_savings_paise / 100:,.2f}",
            styles["Normal"],
        ),
        Spacer(1, 0.8 * cm),
        Paragraph("<b>Spending by FY month</b>", styles["Heading2"]),
        Spacer(1, 0.3 * cm),
    ]

    data = [["Month", "Spent (₹)"]]
    for label, paise in rows:
        data.append([label, f"{paise / 100:,.2f}"])

    table = Table(data, colWidths=[8 * cm, 6 * cm])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#047857")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f4f4f5")]),
            ],
        ),
    )
    story.append(table)
    story.append(Spacer(1, 1 * cm))
    story.append(
        Paragraph(
            "<i>Generated by Personal Finance OS. Not financial advice.</i>",
            styles["Italic"],
        ),
    )
    doc.build(story)
    return buf.getvalue()
